---
title: "Understanding NYC's Graffiti Epidemic"
output: 
  flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(flexdashboard)
library(mapsf)
library(ggplot2)
library(tigris)
library(sf)
library(rvest)
library(dplyr)
library(tidyr)

path <- "/Users/SG/Documents/Programming/nycdsGraffiti/"

df <- read.csv(paste(path, 'graffitiDF.csv', sep = '/'))
monthlyCount <- read.csv(paste(path, 'monthlyCount.csv', sep = '/'))
graffitiPivot <- read.csv(paste(path, 'graffitiPivot.csv', sep = '/'))

monthlyCount$month <- factor(monthlyCount$month, levels = unique(monthlyCount$month))

html <- read_html('https://www.nycbynatives.com/nyc_info/new_york_city_zip_codes.php')


ziplist <- html %>% 
          html_element('table') %>%
          html_table() %>%
          select('X1', 'X4')

ziplist <- ziplist %>%
           transform(X1 = as.character(X1), X4 = as.character(X4)) %>%
           gather(value = zipcode)
           
ziplist <- data.frame(ziplist[,-1])
ziplist <- ziplist %>% rename(zipcode = 1)

zipCount <- df %>%
  group_by(zipcode = as.character(zip_code)) %>%
  summarise(count = n())
           
zipCount <- full_join(ziplist, zipCount, by = 'zipcode') 

zipCount <- zipCount %>%
            replace_na(list(count = 0)) %>%
            arrange(desc(count))
  
zipTop <- zipCount %>% head(20)

# download shapfile (for map)
options(tigris_use_cache = TRUE)
geo <- st_as_sf(zctas(cb = TRUE, starts_with = zipCount$zipcode))
sf_use_s2(FALSE)

zipCount <- merge(geo, zipCount, by.x="ZCTA5CE10", by.y="zipcode")
```

Column {data-width=600}
-----------------------------------------------------------------------


```{r}
mf_map(x = zipCount, 
       var = "count",
       type = "choro",
       pal = "Burg",
       breaks = "quantile",
       border = "white",
       leg_title = "Reported Incidents by Zipcode",
       leg_val_rnd = 0)

mf_title("Graffiti Reports in NYC since 1/30/21")
mf_credits("NYC Open Data / nycbynatives.com", pos = "bottomright")
```

Column {data-width=400}
-----------------------------------------------------------------------


```{r}
ggplot(graffitiPivot[-6,], aes(x="", y=total, fill=borough)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  theme_void() +
  labs(title = 'Which borough is tagged most?',
       fill='Borough')
```

### Monthly Incidents Across All Boroughs

```{r}
ggplot(monthlyCount, aes(x= month, y= count, fill = month)) +
  geom_col() + 
  theme_classic() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x = '',
       y = 'Incidents')
```

